import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";


//components import 
import Header from "@/components/Header";
import Footer from "@/components/Footer";

// theme provider
import {ThemeProvider} from '@/components/ThemeProvider'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <ThemeProvider attribute="class" defaultTheme='light'>
          <Header/>
          {children}
          <Footer/>
        </ThemeProvider>
       
        </body>
    </html>
  );
}
